plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'pl.wolfedu.app'
    compileSdk 35

    defaultConfig {
        applicationId 'pl.wolfedu.app'
        minSdk 24
        targetSdk 35
        versionCode 906001
        versionName '0.9.6-beta.1'
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.2.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
}
