plugins { id 'com.android.application' }

android {
    namespace 'pl.xwolfik.mojdziennik'
    compileSdk 35

    defaultConfig {
        applicationId 'pl.xwolfik.mojdziennik'
        minSdk 24
        targetSdk 35
        versionCode 5
        versionName '2.2.0'
    }

    signingConfigs {
        release {
            def keystorePath = System.getenv('KEYSTORE_FILE')
            def keystorePassword = System.getenv('KEYSTORE_PASSWORD')
            def keyAliasValue = System.getenv('KEY_ALIAS')
            def keyPasswordValue = System.getenv('KEY_PASSWORD')

            if (keystorePath && keystorePassword && keyAliasValue && keyPasswordValue) {
                storeFile file(keystorePath)
                storePassword keystorePassword
                keyAlias keyAliasValue
                keyPassword keyPasswordValue
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}
